{
 "title": "System and Docker Stats",
 "description": "System And Docker Monitoring Template",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(node_uname_info,instance)"
   },
   {
    "name": "Image",
    "query": "label_values(container_cpu_system_seconds_total{image!=\"\"},image)"
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"}) - sum(node_memory_MemFree_bytes{instance=~\"^($Node).*\"}+node_memory_Buffers_bytes{instance=~\"^($Node).*\"}+node_memory_Cached_bytes{instance=~\"^($Node).*\"}) ) / sum(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"}) * 100"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - (avg  (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"^($Node).*\"}[1m])) * 100)"
      }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 - 100 * sum(node_filesystem_free_bytes{instance=~\"^($Node).*\"}) / sum(node_filesystem_size_bytes{instance=~\"^($Node).*\"}) "
      }
     ]
    },
    {
     "title": "Host cpu usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"^($Node).*\"}[1m])) * 100)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Host memory usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100*(node_memory_MemTotal_bytes{instance=~\"^($Node).*\"} - node_memory_MemFree_bytes{instance=~\"^($Node).*\"} - node_memory_Buffers_bytes{instance=~\"^($Node).*\"} - node_memory_Cached_bytes{instance=~\"^($Node).*\"}) / node_memory_MemTotal_bytes{instance=~\"^($Node).*\"} ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Host Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance,device) (rate(node_network_receive_bytes_total{device!~\"^(lo|docker|veth|flannel|virbr).*\",instance=~\"^($Node).*\"}[1m]))",
       "legendFormat": "-> {{ instance}} {{ device }}"
      }
     ]
    },
    {
     "title": "Host disk usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - 100 * ( sum by (instance) (node_filesystem_free_bytes{instance=~\"^($Node).*\"}) /sum  by (instance) (node_filesystem_size_bytes{instance=~\"^($Node).*\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_cpu_usage_seconds_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m])) by (instance, name))",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name))",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name) / sum(container_spec_memory_limit_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"}) by (instance, name) * 100)",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "expr": "container_spec_memory_limit_bytes{image=~\"($Image)\",instance=~\"^($Node).*\"} ",
     "legendFormat": "{{ instance}} {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (instance,name) (rate(container_network_receive_bytes_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m] ) ))",
     "legendFormat": "-> {{ instance }}  {{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (instance, name) (rate(container_network_transmit_bytes_total{image=~\"($Image)\",instance=~\"^($Node).*\"}[1m] ) ))",
     "legendFormat": "<- {{ instance}} {{ name }}"
    }
   ]
  }
 ]
}